### PR TITLE
Add more tests

### PR DESCRIPTION
**Pull request by psyomn**
This PR adds more tests, switches to rebar3, and declares `jiffy` as a testing dependency.

I'm not sure if these tests will be any useful to you, but I decided to share some of my work
while I was evaluating this library.

Feel free to close if said tests are unwanted.

### CODE REVIEW

**Comment by seriyps** [comment]
Hi. Thank you, it looks good for me. However, I no longer have merge access to this repo. So, if anyone from @ostrovok-team would be able to merge it, it would be really nice!

**Comment by vanadium23** [comment]
@psyomn thank you for pull request. Everything is good to me, but do we need to include rebar3 binary file to repo? I've searched through erlang repos on github, and it is not included in most one.

**Comment by seriyps** [comment]
I would say it's better to not include it, unless your code have some hard dependency from rebar3 version or you are shipping standalone product.

**Comment by psyomn** [comment]
Thanks for the quick feedback! I have removed the binary `rebar3` commit!

**Comment by vanadium23** [comment]
LGTM, thank you for help :tada:

**Pull request merged**
